#!/bin/bash

count=0

ID="$(ip link | awk '/state UP/ {print $2}')"
SSID="$(iwgetid -r)"

net_stat () {
	if (ping -c 1 archlinux.org || ping -c 1 google.com || ping -c 1 bitbucket.org || ping -c 1 github.com || ping -c 1 sourceforge.net) &>/dev/null; then
		if [[ $ID == e* ]]; then
			echo "Connected"
			echo "images/icons/tray/wired.svg"
		else
			echo "Connected"
			echo "images/icons/tray/wifi.svg"
		fi
	else
		echo "Offline"
		echo "images/icons/tray/no-wifi.svg"	
	fi
}

if [[ $1 == '--stat' ]]; then
	net_stat | head -n1
elif [[ $1 == '--icon' ]]; then
	net_stat | tail -n1
fi
