#!/usr/bin/env bash

CFG="$HOME/.config/eww/sidebar"

close_eww() {
	eww --config "$CFG" close sidebar
}

## Options #############################################
if  [[ $1 = "--lock" ]]; then
	close_eww
    lock.sh

elif  [[ $1 = "--logout" ]]; then
	close_eww
    #openbox --exit
    bspc quit

elif  [[ $1 = "--suspend" ]]; then
	close_eww
	amixer set Master mute
	systemctl suspend

elif  [[ $1 = "--reboot" ]]; then
	close_eww
    systemctl reboot

elif  [[ $1 = "--shutdown" ]]; then
	close_eww
    systemctl poweroff

## Help Menu #############################################
else
echo "
Available options:
--lock	--logout	--suspend	--reboot	--shutdown
"
fi
