#!/bin/bash

# Get Volume
get_volume() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $4}' | tr -d '[]'`
		echo "$volume"
	else
		echo "Mute"
	fi
}

get_volume_clean() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		volume=`amixer get Master | tail -n1 | awk -F ' ' '{print $4}' | tr -d '[]' | cut -d % -f 1`
		echo "$volume"
	else
		echo "Mute"
	fi
}

# Get icons
get_icon() {
	vol="$(get_volume)"
	current="${vol%%%}"
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		if [[ "$current" -eq "0" ]]; then
			echo "images/icons/tray/mute.svg"
		elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
			echo "images/icons/tray/volume1.svg"
		elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
			echo "images/icons/tray/volume2.svg"
		elif [[ ("$current" -ge "60") && ("$current" -le "100") ]]; then
			echo "images/icons/tray/volume3.svg"
		fi
	else
		echo "images/icons/tray/mute.svg"
	fi
}

# Increase Volume
inc_volume() {
	amixer -Mq set Master,0 1%+ unmute
}

# Decrease Volume
dec_volume() {
	amixer -Mq set Master,0 1%- unmute
}

# Toggle Mute
toggle_mute() {
	status=`amixer get Master | tail -n1 | grep -wo 'on'`

	if [[ "$status" == "on" ]]; then
		pactl set-sink-mute `pactl get-default-sink` toggle
	else
		pactl set-sink-mute `pactl get-default-sink` toggle
	fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--getclean" ]]; then
	get_volume_clean
elif [[ "$1" == "--icon" ]]; then
	get_icon
elif [[ "$1" == "up" ]]; then
	inc_volume
elif [[ "$1" == "down" ]]; then
	dec_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
else
	get_volume
fi
