#!/usr/bin/env bash

CFG="$HOME/.config/eww/wifimenu"
EWW=`which eww`
cache="$HOME/.config/eww/scripts/wifimenu/networks"
cacheselected="$HOME/.config/eww/scripts/wifimenu/selected"

if  [[ $1 = "--update" ]]; then
    echo '...'
    netsraw=$(echo `nmcli device wifi list`)
    count=$(($(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | head -6 | wc -l)-1))
    net1=$(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | sed '2q;d'| cut -d ' ' -f 1)
    net2=$(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | sed '3q;d'| cut -d ' ' -f 1)
    net3=$(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | sed '4q;d'| cut -d ' ' -f 1)
    net4=$(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | sed '5q;d'| cut -d ' ' -f 1)
    net5=$(echo $netsraw | sed 's/..:..:..:..:..:.. /\n/g' | sed '6q;d'| cut -d ' ' -f 1)
    echo -e "$net1|$net2|$net3|$net4|$net5" > "$cache"
fi

if  [[ $1 = "--getselected" ]]; then
    echo "Active: $(iwgetid -r)"
fi

if  [[ $1 = "--nets" ]]; then
    cat $cache
fi

if  [[ $1 = "--sets" ]]; then
    cat $cache | cut -d '|' -f $2 > "$HOME/.config/eww/arin/scripts/wifimenu/selected"
    ${EWW} --config "$CFG" close wifimenu
    `../wifimenu/toggle_passwordbox`
fi

if  [[ $1 = "--connect" ]]; then
    ${EWW} --config "$CFG" close passwordbox
    prefix="nmcli dev wifi connect"
    selected=$(cat "$HOME/.config/eww/arin/scripts/wifimenu/selected")
    suffix="password"
    cmd="$prefix $selected $suffix \"$2\""
    eval $cmd
fi
