#!/bin/bash

ICONBLANK="$HOME/.config/eww/images/icons/workspaces/blank.png"
ICONOCCUPIED="$HOME/.config/eww/images/icons/workspaces/occupied.png"
ICONACTIVE="$HOME/.config/eww/images/icons/workspaces/active.png"


main() {
    STATUS=$(wmctrl -l | cut -d ' ' -f 3 | grep $1)
    
    if [[ -z "$STATUS" ]]; then
        echo "$ICONBLANK"
    else
        echo "$ICONOCCUPIED"
    fi
}

if [[ "$1" == "$(xdotool get_desktop)" ]]; then
    echo "$ICONACTIVE"
else
    main $1
fi
