#!/bin/bash

ICONBLANK="$HOME/.config/eww/images/icons/workspaces/blank.png"
ICONOCCUPIED="$HOME/.config/eww/images/icons/workspaces/occupied.png"
ICONACTIVE="$HOME/.config/eww/images/icons/workspaces/active.png"


main() {
    STATUS=$(wmctrl -l | cut -d ' ' -f 3 | grep $SPACE)
    
    if [[ -z "$STATUS" ]]; then
        echo "$ICONBLANK"
    else
        echo "$ICONOCCUPIED"
    fi
}


SPACE="0"

if [[ $1 == "--2" ]]; then
    SPACE="1"
elif [[ $1 == "--3" ]]; then
    SPACE="2"
elif [[ $1 == "--4" ]]; then
    SPACE="3"
elif [[ $1 == "--5" ]]; then
    SPACE="4"
fi

ACTIVE=$(wmctrl -d | grep '*' | cut -d ' ' -f 1)

if [[ "$SPACE" == "$ACTIVE" ]]; then
    echo "$ICONACTIVE"
else
    main
fi
