#!/usr/bin/env bash

CFG="$HOME/.config/eww/soundmenu/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
eww --config "$CFG" open --toggle soundmenu
