#!/usr/bin/env bash

CFG="$HOME/.config/eww/sidebar/"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
${EWW} --config "$CFG" open --toggle sidebar
