#!/bin/bash

################################################################
######                    BSPWM CONFIG                    ######
################################################################

################################
###     Launch Programs      ###
################################

pkill sxhkd
sxhkd &

pkill compton
compton &

#Restore wallpaper
nitrogen --restore

#Set up 5 workspaces on active monitor
SCREEN=$(xrandr -q | grep " connected" | grep HDMI | cut -d " " -f1)
LAPTOP=$(xrandr -q | grep " connected" | grep eDP | cut -d " " -f1)
LEN=${#SCREEN}
if test $LEN -gt 0
then
    xrandr --output $SCREEN --primary --mode 1920x1080 --rotate normal --output $LAPTOP --mode 1920x1080 --rotate normal --right-of $SCREEN
    sleep 2s
    bspc monitor -f $SCREEN
    bspc monitor $SCREEN -d 1 2 3 4 5
    bspc monitor -f $LAPTOP
    bspc monitor $LAPTOP -d 6 7 8
else
    bspc monitor $LAPTOP -d 1 2 3 4 5
fi



sleep 1s
# Launching polybar and plank
bash $HOME/.config/polybar/launch.sh --docky

################################
###      Set Parameters      ###
################################
#Fix pointer
xsetroot -cursor_name left_ptr

#Gaps and border thickness
bspc config border_width	0
#bspc config active_border_color '#E0E0E0'
#bspc config normal_border_color '#2C2C2C'
#bspc config focused_border_color '#E0E0E0'
bspc config window_gap		0
bspc config automatic_scheme    automatic

bspc config split_ratio		0.50
bspc config focus_follows_pointer	false
bspc config pointer_modifier	mod1

# Starting SXHKD Keyboard Daemon
pgrep -x sxhkd > /dev/null || sxhkd &


################################
###        BSPC Rules        ###
################################

bspc rule -a Gnome-calculator state=floating
bspc rule -a Gnome-terminal state=floating
bspc rule -a Gnome-system-monitor state=floating
bspc rule -a cinnamon-settings state=floating
bspc rule -a "cinnamon-settings network" state=floating
