#! /bin/sh

xset -dpms # Disables Energy Star features
xset s off # Disables screen saver
xinput set-prop 14 338 1 #enable natural scrolling on touchpad
xinput set-prop 14 365 1 #enable tap to click on touchpad

pkill sxhkd
# Starting SXHKD Keyboard Daemon
sxhkd &

pkill picom
sleep 1
picom &

nitrogen --restore

killall mpd 
sleep 1
mpd &

mpc update

#Set up 5 workspaces on active monitor
SCREEN=$(xrandr -q | grep " connected" | grep HDMI | cut -d " " -f1)
LAPTOP=$(xrandr -q | grep " connected" | grep eDP | cut -d " " -f1)
LEN=${#SCREEN}
if test $LEN -gt 0
then
    xrandr --output $SCREEN --auto --left-of $LAPTOP
    xrandr --output $SCREEN --same-as $LAPTOP
    sleep 2s
    bspc monitor -f $SCREEN
    bspc monitor $SCREEN -d 1 2 3 4 5
    bspc monitor -f $LAPTOP
    bspc desktop -f 1
else
    bspc monitor $LAPTOP -d 1 2 3 4 5
    bspc desktop -f 1
fi

#############RUNNING EWW#############
EWW=`which eww`
CFG="$HOME/.config/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
killall eww
run_eww() {
	eww --config "$CFG" open bar
}

## Launch or close widgets accordingly
run_eww
######################################

################################
###      Set Parameters      ###
################################
#Fix pointer
xsetroot -cursor_name left_ptr

#Gaps and border thickness
bspc config border_width	1
bspc config active_border_color '#5C5C5C'
bspc config normal_border_color '#5C5C5CC'
bspc config focused_border_color '#9C9C9C'
bspc config window_gap		5
bspc config automatic_scheme    automatic

bspc config split_ratio		0.50
bspc config focus_follows_pointer	false
bspc config pointer_modifier	mod1

################################
###        BSPC Rules        ###
################################

bspc rule -a scpad sticky=on state=floating rectangle=800x400+560+0

bspc rule -a Zathura state=tiled
#bspc rule -a kitty state=floating rectangle=600x400
bspc rule -a Gnome-calculator state=floating
bspc rule -a Gnome-system-monitor state=floating
